apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.jvb.fullname" . }}
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
data:
  JVB_BREWERY_MUC: '{{ .Values.jvb.breweryMuc }}'
  JVB_PORT: '{{ .Values.jvb.UDPPort }}'
  JVB_STUN_SERVERS: '{{.Values.jvb.stunServers }}'
  {{- if .Values.jvb.enableTCP }}
  JVB_TCP_PORT: '{{ .Values.jvb.TCPPort }}'
  JVB_TCP_HARVESTER_DISABLED: '0'
  {{- else }}
  JVB_TCP_HARVESTER_DISABLED: '1'
  {{- end }}
  XMPP_SERVER: '{{ include "jitsi-meet.xmpp.server" . }}'
  {{- range $key, $value := .Values.jvb.extraEnvs }}
  {{- if not (kindIs "invalid" $value) }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.jvb.metrics.enabled }}
  JVB_ENABLE_APIS: 'rest,colibri'
  {{- else }}
  JVB_ENABLE_APIS: 'rest'
  {{- end }}
